# Starting numpy

# 1-D array

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
print(type(arr))

<class 'numpy.ndarray'>


# 0-D array

In [3]:
zeroD = np.array(42)
print(zeroD)

42


In [4]:
print(type(zeroD))

<class 'numpy.ndarray'>


# 2-D array

In [5]:
twoD = np.array([[1,2,3],[4,5,6]])
print(twoD)

[[1 2 3]
 [4 5 6]]


# 2D with 3 arrays

In [20]:
twoD = np.array([[1,2,3,4]])
print(twoD.ndim)

2


In [8]:
twoD = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
twoD = np.array([[10,20,30],[100,110,120]])
print(twoD)

[[ 10  20  30]
 [100 110 120]]


In [10]:
print(twoD.ndim)

2


In [18]:
print(twoD[1,1])

110


# 3-D array

In [15]:
threeD = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(threeD)
print(threeD.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [17]:
print(threeD[0, 2])


[7 8 9]


In [11]:
threeD = np.array([[[1,2,3] ,[4,5,6]],[[7,8,9],[10,11,12]]])
print(threeD)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
print(threeD.ndim)


3


In [13]:
print(threeD[0,1,1])


5


# ND array

In [14]:
arr = np.array([1,2,3], ndmin = 5)
print(arr)
print(arr.ndim)

[[[[[1 2 3]]]]]
5


In [25]:
arr = np.array([[1,2],[3,4],[5,6],[7,8]], ndmin = 4)
print(arr)


[[[[1 2]
   [3 4]
   [5 6]
   [7 8]]]]


# Transposition

In [26]:
arr = np.array([[1,2,3],[4,5,6]])
print(f"Original array: \n{arr}")
transpose_arr = arr.transpose()
print(f"Transposed array: \n{transpose_arr}")

Original array: 
[[1 2 3]
 [4 5 6]]
Transposed array: 
[[1 4]
 [2 5]
 [3 6]]


# Ufuncs in numpy

In [28]:
x = [1,2,3,4]
y = [5,6,7,8]
z = np.add(x,y)
print(z)
print(type(z))
print(type(np.add))

[ 6  8 10 12]
<class 'numpy.ndarray'>
<class 'numpy.ufunc'>


# Conversion of py func into ufunc

In [30]:
def myadd(x,y):
    return x + y
myadd = np.frompyfunc(myadd, 2, 1)
print(myadd([1,2,3,4],[5,6,7,8]))

[6 8 10 12]


# For multiplication in numpy 
options:
np.dot(A,B),
A @ B,
np.matmul(A,B)

In [17]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,5,6])
C = A * B
print(C)

[ 4 10 18]


In [3]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
C = np.dot(A,B)
print(C)


[[19 22]
 [43 50]]


# Exponentiation in numpy

In [4]:
A = np.array([1,2,3])
B = np.power(A, 2)
print(B)

[1 4 9]


In [5]:
A = np.array([1,2,3])
B = A ** 2
print(B)

[1 4 9]


In [9]:
A = np.array([1,2,3])
B = 2 ** A
print(B)

[2 4 8]


# Modulus in numpy

In [7]:
A = np.array([10,22,30])
B = np.array([4,5,6])
C = np.mod(A,B)
print(C)

[2 2 0]


In [8]:
A = np.array([10,22,30])
B = np.array([4,5,6])
C = A % B
print(C)

[2 2 0]


In [19]:
def mymul(x,y):
    return x ** y
mymul = np.frompyfunc(mymul, 2, 1)
print(mymul([1,2,3,4],[5,6,7,8]))

[1 64 2187 65536]


# Log array in Numpy

In [23]:
in_array = [2, 3, 4, 5, 6, 2**8]
print(f"This is the array given: {in_array}")
out_array = np.log(in_array)
print(f"This is the log array: {out_array}")
print("\nnp.log(4**4):", np.log(4**4))


This is the array given: [2, 3, 4, 5, 6, 256]
This is the log array: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 5.54517744]

np.log(4**4): 5.545177444479562


# Finding LCM

In [31]:
arr = np.array([3, 6, 9])
lcm = np.lcm.reduce(arr)
print(lcm)

18


# Searching arrays Finds indexes

In [42]:
arr = np.array([1,2,3,4,5,1,2,6,7,1,2,3,6,1,-1])
target = np.where(arr==1 )
sec_target = np.where(arr == 2)
evry = np.all(arr)
print(target)
print(sec_target)
print(type(target))
print(evry)

(array([ 0,  5,  9, 13]),)
(array([ 1,  6, 10]),)
<class 'tuple'>
True


# Finding indexes of even numbers in array

In [41]:
arr = np.array([1,2,3,4,5,1,2,6,7,1,2,3,6,1,-1])
even = np.where(arr%2 ==0 )
print(even)

(array([ 1,  3,  6,  7, 10, 12]),)


# Sorting 

In [43]:
arr = np.array([1,6,9,0,13,56,3,4,7,2,3,9])
sorted_arr = np.sort(arr)
print(sorted_arr)

[ 0  1  2  3  3  4  6  7  9  9 13 56]


# Sorting for large array with diff datatype values, gives output in string type and inaccuracy in integers

In [51]:
arr = np.array(['orange', 'apple','banana',1,6,9,0,13,56,3,4,7,2,3,9,True, False,True, False,True, False])
sorted_arr = np.sort(arr)
print(sorted_arr)
print(type(sorted_arr))
print(sorted_arr[1])
print(type(sorted_arr[1]))

['0' '1' '13' '2' '3' '3' '4' '56' '6' '7' '9' '9' 'False' 'False' 'False'
 'True' 'True' 'True' 'apple' 'banana' 'orange']
<class 'numpy.ndarray'>
1
<class 'numpy.str_'>


# Saving and loading the array

In [61]:
arr = np.array([[1,2,3],[4,5,6]])
np.save('C:/Users/ACER/OneDrive/Desktop/jupyter/.npy', arr)


In [62]:
loaded_array = np.load('C:/Users/ACER/OneDrive/Desktop/jupyter/.npy')
print(loaded_array)

[[1 2 3]
 [4 5 6]]


# Saving and loading the array in txt extension

In [64]:
arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('C:/Users/ACER/OneDrive/Desktop/jupyter/.txt', arr)

In [66]:
loaded = np.loadtxt('C:/Users/ACER/OneDrive/Desktop/jupyter/.txt')
print(loaded)

[[1. 2. 3.]
 [4. 5. 6.]]
